(source gnu)
(source marmalade)
(source melpa)

(depends-on "flx-ido")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "magit-gh-pulls")
(depends-on "pallet")
(depends-on "rainbow-mode")
(depends-on "scss-mode")
(depends-on "tangotango-theme")